### ISSUE TITLE
Remove complete lines

### ISSUE THREAD

**Issue by pkierat-epam** [EPAM-Online-Courses/teatrees-prejap3#13]
## User story

```
As a player,
I want complete lines to be removed from the playfield,
So that I have more room to put new blocks.
```

## Acceptance criteria

1. A line that is filled with bricks completely, i.e. without gaps, is removed from the playfield.
2. Lines that are above it, are moved down one position.

**Comment by chowaniecpiotr** [comment]
I will do this task.
