### ISSUE TITLE
Add posibility to pause a game

### ISSUE THREAD

**Issue by pkierat-epam** [EPAM-Online-Courses/teatrees-prejap3#25]
1. User story: sometimes when I play, I need to stop and do something else. Add a possibility to pause the game with a key (by default p)
2. Acceptance criteria: program can be paused and rerun with the same key.
3. Additional points: let user decide how many seconds program re-run after pressing pause key (for example:
 - press p -> PAUSE
 - press 3 -> nothing happens!
 - press p -> Programs wait 3 seconds more and runs again.

I did hide my comment because Im afraid people may not check what this comment was about and think someone has already decided to accomplish the task

**Comment by macblok** [comment]
I will work on this task.
